--- 
    matrix: 
      include: 
        - 
          before_script: "pip install docker-compose"
          language: python
          python: 
            - "3.6"
          script: 
            - "docker-compose run --rm server sh -c "python manage.py test"
          services: 
            - docker
        - 
          language: node_js
            node_js: 
              - "14"
          addons: 
            chrome: stable
          before_script:
            - yarn global add @angular/cli
          cache:
            yarn: true
            directories: 
              - node_modules
          dist: trusty
          install: 
            - "npm install
          script: 
            - "docker-compose run --rm client sh -c "ng build --prod"
          sudo: false
          
          deploy:
            provider: pages
            skip-cleanup: true
            local-dir: ./dist/
    