version: '3'

services:

#Setup server container
    server:
        build: 
            context: ./server
        ports:
            - "8000:8000"
        volumes:
            - ./server:/server
        command: sh -c "python manage.py runserver 0.0.0.0:8000"
        
    client:
        build:
            context: ./client
        ports:
            - "4200:4200"
        volumes:
            - "/client/node_modules"
            - "./client:/client"