version: '3'

services:

#Setup server container
    server:
        build: 
            context: ./server
        ports:
            - "8000:8000"
        volumes:
            - ./server:/server
        command: sh -c "python manage.py runserver 0.0.0.0:8000"
        environment:
            - DB_HOST=db
            - DB_NAME=app
            - DB_USER=postgres
            - DB_PASS=supersecretpassword
        depends_on:
            - db

    db:
        image: postgres:13-alpine
        environment:
            - POSTGRES_DB=server
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=supersecretpassword
        
    client:
        build:
            context: ./client
        ports:
            - "4200:4200"
        volumes:
            - "/client/node_modules"
            - "./client:/client"
        command: sh -c "ng serve --host 0.0.0.0 --poll 1"
        depends_on: 
            - server